# Generated by Django 4.0.3 on 2022-03-11 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="CityWeather",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("coord", models.JSONField()),
                ("base", models.CharField(max_length=255)),
                ("main", models.JSONField()),
                ("visibility", models.IntegerField()),
                ("wind", models.JSONField()),
                ("clouds", models.JSONField()),
                ("dt", models.PositiveBigIntegerField()),
                ("sys", models.JSONField()),
                ("timezone", models.IntegerField()),
                ("external_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("cod", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.IntegerField()),
                ("main", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                ("city_weather", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="weather", to="weather_app_client.cityweather")),
            ],
        ),
    ]
